# Generated by Django 4.2.6 on 2023-10-25 09:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('semestre', models.IntegerField()),
                ('anno', models.CharField(choices=[('1', '1° ANNO'), ('2', '2° ANNO'), ('3', '3° ANNO'), ('F', 'FUORICORSO')], max_length=1)),
                ('crediti', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('link', models.URLField(blank=True, null=True)),
                ('dipartimento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Esame',
            fields=[
                ('corso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.corso')),
                ('voto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(30.5)])),
                ('data_esame', models.DateField(blank=True, null=True)),
            ],
            bases=('event.corso',),
        ),
        migrations.CreateModel(
            name='Lezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno_settimana', models.CharField(choices=[('L', 'Lunedì'), ('M', 'Martedì'), ('ME', 'Mercoledì'), ('G', 'Giovedì'), ('V', 'Venerdì')], max_length=2)),
                ('orario_inizio', models.TimeField()),
                ('orario_fine', models.TimeField()),
                ('aula', models.CharField(max_length=50)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.corso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.docente')),
            ],
        ),
        migrations.AddField(
            model_name='corso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.docente'),
        ),
    ]
