# Generated by Django 3.2 on 2023-11-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='anno',
            field=models.CharField(choices=[('1', '1° ANNO'), ('2', '2° ANNO'), ('3', '3° ANNO')], max_length=1),
        ),
    ]
