# Generated by Django 3.2 on 2023-11-05 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anno_accademico',
            field=models.CharField(choices=[('1', '1° ANNO'), ('2', '2° ANNO'), ('3', '3° ANNO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message="L'email deve seguire il formato: nome.cognome@studenti.unicam.it", regex='^[a-zA-Z]+\\.[a-zA-Z]+@studenti\\.unicam\\.it$')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unicorn')], max_length=10, null=True),
        ),
    ]
